<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBmeirnx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBmeirnx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBmeirnx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBmeirnx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBmeirnx\appProdProjectContainer([
    'container.build_hash' => 'Bmeirnx',
    'container.build_id' => '8b1b9b25',
    'container.build_time' => 1637965147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBmeirnx');
